%% THERMAL CONTROL SIZING 
clc
clear

%% DATA
i_orb=96.97;
ecliptic=23.44; 
h=320;
r_orb = h + astroConstants(23);
Q_max = 1.3*1400; % maximum heat generated by internal components
Q_min = 560-128; % minimum heat generated by internal components
x_bus = 2;
y_bus = 1.9;
z_bus = 1.74;
r_aladin = 0.75;
z_aladin = 4.6-z_bus;
T_sc_max = 50 + 273.15; % maximum temperature reachable by the s/c
T_sc_min = -20 + 273.15; % minimum temperature reachable by the s/c

%% GEOMETRY FOR THE PROBLEM
R_pl = astroConstants(23);
A_tot = 2*pi*r_aladin*z_aladin + 2*x_bus*z_bus + 2*y_bus*z_bus + x_bus*y_bus; %la prima aerea serve?
R = sqrt(A_tot/(4*pi));

F_pl= 1/2*(1 - (sqrt((h/R_pl)^2 + 2* h/R_pl))/(1 + h/R_pl));
A_cross_pl = A_tot * F_pl; 

A_cross_Sun = pi * R^2;

A_space = A_tot - A_cross_pl;

%% HEAT SOURCES 
% DATA
q0 = 1367.5; % solar heat flux at 1 AU
a = 0.4; % planetary albedo constant
sigma = 5.67 * 10^-8; % Boltzmann constant
epsilon_pl = 0.8; % infrared emissivity of the planet
T_pl = 288; % Temperature of the planet SEEN FROM SPACE, oppure 255
%ricordarsi che MATLAB vuole gli anngoli in raadianti
% COMPUTATIONS, HEAT FLUXES 
q_sun = q0; %già tralasciato il valore che si annulla
q_albedo = q_sun * a * (R_pl/r_orb)^2;
q_IR = sigma * epsilon_pl * T_pl^4 * (R_pl/r_orb)^2;

%% HEAT POWER
% DATA
alpha_sc_WP = 0.25;
alpha_sc_AK = 0.4;
epsilon_sc_WP = 0.88;
epsilon_sc_AK = 0.71;
alpha_sc = 0.2*alpha_sc_AK + 0.8*alpha_sc_WP; % equivalent satellite solar absorbtivity
epsilon_sc = 0.2*epsilon_sc_AK + 0.8*epsilon_sc_WP; % equivalent satellite surface IR emissivity
T_space = 3; 

% COMPUTATIONS
Q_sun = A_cross_Sun * alpha_sc * q_sun;
Q_albedo = A_cross_pl * alpha_sc * q_albedo;
Q_IR = A_cross_pl * epsilon_sc * q_IR;

% Q_emitted = sigma * epsilon_sc * A_space * (T_sc^4 - T_space^4);

%% HOT CASE
A_D_rad_LIM = 4; % maximum area I allow my deployable radiators to be

T_sc_hot = ((Q_sun + Q_albedo + Q_IR + Q_max)/(sigma * epsilon_sc * A_space) + T_space^4)^(1/4);
if T_sc_hot >= T_sc_max - 15 %qua ci va il MENO
    % RADIATORS DATA 
    epsilon_rad = 0.92;
    
    % BODY MOUNTED RADIATOR COMPUTATION
    fun_A_BM_rad = @(x) (Q_sun + Q_albedo + Q_IR + Q_max) / (epsilon_sc * (A_space - x) / (epsilon_rad * x) + 1) - sigma * epsilon_rad * x * ((T_sc_max -15)^4 - T_space^4);
    A_BM_rad_1 = -(A_space*epsilon_sc*sigma*T_space^4 - A_space*epsilon_sc*sigma*T_sc_max^4 + 60*A_space*epsilon_sc*sigma*T_sc_max^3 - 1350*A_space*epsilon_sc*sigma*T_sc_max^2 + 13500*A_space*epsilon_sc*sigma*T_sc_max + Q_IR + Q_albedo + Q_max + Q_sun - 50625*A_space*epsilon_sc*sigma)/(50625*epsilon_sc*sigma - 50625*epsilon_rad*sigma - 13500*T_sc_max*epsilon_sc*sigma + 13500*T_sc_max*epsilon_rad*sigma - T_space^4*epsilon_sc*sigma + T_space^4*epsilon_rad*sigma + 1350*T_sc_max^2*epsilon_sc*sigma - 60*T_sc_max^3*epsilon_sc*sigma + T_sc_max^4*epsilon_sc*sigma - 1350*T_sc_max^2*epsilon_rad*sigma + 60*T_sc_max^3*epsilon_rad*sigma - T_sc_max^4*epsilon_rad*sigma);
    A_BM_rad_2 = fsolve(fun_A_BM_rad, 1000);

    if A_BM_rad_1 > 0.8*A_space %io metterei anche 0.6 o 0.7
        % DEPLOYABLE RADIATORS COMPUTATION
        fun_A_D_rad = @(x) (Q_sun + Q_albedo + Q_IR + Q_max) / (epsilon_sc * (A_space - x) / (epsilon_rad * x)) - sigma * epsilon_rad * x * ((T_sc_max -15)^4 - T_space^4);
        A_D_rad = fsolve(fun_A_D_rad, 100);

        if A_D_rad > A_D_rad_LIM 
            % ACTIVE COOLER COMPUTATION
            Q_emitted = sigma * epsilon_sc * (A_space - A_D_rad_LIM) * ((T_sc_max - 15)^4 - T_space^4);
            Q_cool = sigma * epsilon_rad * A_D_rad_LIM * ((T_sc_max - 15)^4 - T_space^4);

        end
    end

else
    fprintf('NO COOLERS REQUIRED')
end

%% COLD CASE
T_sc_cold = ((Q_IR + Q_min)/(sigma * epsilon_sc * A_space) + T_space^4)^(1/4);
if T_sc_cold <= T_sc_min + 15
    % HEATER COMPUTATION
    Q_emitted_cold = sigma * epsilon_sc * A_space * ((T_sc_min + 15)^4 - T_space^4);
    Q_HEATER = Q_emitted_cold - Q_IR - Q_min; 

else
    fprintf('NO HEATERS REQUIRED')
end